ROOT_PATH = "/root/.gazebo/models"
HEIGHTMAP_SDF_PATH = ROOT_PATH + '/heightmap_test/model.sdf'
HIGH_BOUND_HEIGHT_DIFF = 0.45#1
MAX_ROUGHNESS = 45#55
ROUGHNESS_COEF = 0.5
HD_COEF = 0.5
ROBOT_RADIUS = 0.5#1.93
INNER_RADIUS = ROBOT_RADIUS
OUTER_RADIUS = ROBOT_RADIUS + 0.3
CURVE_AVG_STEP = 0.05
CURVATURE_THRESHOLD = 30
DIST_FROM_PATH = 0.5
MAX_ITERATIONS_COUNT = 5
MAP_SIZE_WORDS = ['<collision', '<heightmap', '<size']
MAP_PATH_WORDS = ['<collision', '<heightmap', '<uri']
MAP_POS_WORDS = ['<collision', '<heightmap', '<pos']
ORIENT_BOUND = 47
START_GRID_RANGE = 2
MAX_ITER_COUNT = 500
GOAL_VERTICE_DIST = 10
GRID_SIZE = 1# in meters
DIST_OFFSET = 10
EXPLOSION_RADIUS = 20
HIGH_PROB_VALUE = 0.9

# HEIGHTMAP BOUNDARY INDICES

COL_RANGE = [171, 174]
ROW_RANGE = [260, 263]

